# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDB-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB-SwiftUI
 pod 'Kingfisher', '~> 5.0'
end
